using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Lib.Settings
{
    using System.IO;
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Este código foi gerado por uma ferramenta.
    //     Versão de Tempo de Execução:4.0.30319.42000
    //
    //     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
    //     o código for regenerado.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
    public partial class ResourceCompile
    {

        private string preprocessorDefinitionsField;

        private string cultureField;

        private string includeField;

        /// <observações/>
        public string PreprocessorDefinitions
        {
            get
            {
                return this.preprocessorDefinitionsField;
            }
            set
            {
                this.preprocessorDefinitionsField = value;
            }
        }

        /// <observações/>
        public string Culture
        {
            get
            {
                return this.cultureField;
            }
            set
            {
                this.cultureField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
    public partial class ClCompile
    {

        private string warningLevelField;

        private string optimizationField;

        private string functionLevelLinkingField;

        private string intrinsicFunctionsField;

        private string sDLCheckField;

        private string additionalIncludeDirectoriesField;

        private string inlineFunctionExpansionField;

        private string debugInformationFormatField;

        private string preprocessorDefinitionsField;

        private string minimalRebuildField;

        private string runtimeLibraryField;

        private string precompiledHeaderField;

        private string browseInformationField;

        private string precompiledHeaderOutputFileField;

        private string assemblerOutputField;

        private string favorSizeOrSpeedField;

        private string stringPoolingField;

        private string includeField;

        /// <observações/>
        public string WarningLevel
        {
            get
            {
                return this.warningLevelField;
            }
            set
            {
                this.warningLevelField = value;
            }
        }

        /// <observações/>
        public string Optimization
        {
            get
            {
                return this.optimizationField;
            }
            set
            {
                this.optimizationField = value;
            }
        }

        /// <observações/>
        public string FunctionLevelLinking
        {
            get
            {
                return this.functionLevelLinkingField;
            }
            set
            {
                this.functionLevelLinkingField = value;
            }
        }

        /// <observações/>
        public string IntrinsicFunctions
        {
            get
            {
                return this.intrinsicFunctionsField;
            }
            set
            {
                this.intrinsicFunctionsField = value;
            }
        }

        /// <observações/>
        public string SDLCheck
        {
            get
            {
                return this.sDLCheckField;
            }
            set
            {
                this.sDLCheckField = value;
            }
        }

        /// <observações/>
        public string AdditionalIncludeDirectories
        {
            get
            {
                return this.additionalIncludeDirectoriesField;
            }
            set
            {
                this.additionalIncludeDirectoriesField = value;
            }
        }

        /// <observações/>
        public string InlineFunctionExpansion
        {
            get
            {
                return this.inlineFunctionExpansionField;
            }
            set
            {
                this.inlineFunctionExpansionField = value;
            }
        }

        /// <observações/>
        public string DebugInformationFormat
        {
            get
            {
                return this.debugInformationFormatField;
            }
            set
            {
                this.debugInformationFormatField = value;
            }
        }

        /// <observações/>
        public string PreprocessorDefinitions
        {
            get
            {
                return this.preprocessorDefinitionsField;
            }
            set
            {
                this.preprocessorDefinitionsField = value;
            }
        }

        /// <observações/>
        public string MinimalRebuild
        {
            get
            {
                return this.minimalRebuildField;
            }
            set
            {
                this.minimalRebuildField = value;
            }
        }

        /// <observações/>
        public string RuntimeLibrary
        {
            get
            {
                return this.runtimeLibraryField;
            }
            set
            {
                this.runtimeLibraryField = value;
            }
        }

        /// <observações/>
        public string PrecompiledHeader
        {
            get
            {
                return this.precompiledHeaderField;
            }
            set
            {
                this.precompiledHeaderField = value;
            }
        }

        /// <observações/>
        public string BrowseInformation
        {
            get
            {
                return this.browseInformationField;
            }
            set
            {
                this.browseInformationField = value;
            }
        }

        /// <observações/>
        public string PrecompiledHeaderOutputFile
        {
            get
            {
                return this.precompiledHeaderOutputFileField;
            }
            set
            {
                this.precompiledHeaderOutputFileField = value;
            }
        }

        /// <observações/>
        public string AssemblerOutput
        {
            get
            {
                return this.assemblerOutputField;
            }
            set
            {
                this.assemblerOutputField = value;
            }
        }

        /// <observações/>
        public string FavorSizeOrSpeed
        {
            get
            {
                return this.favorSizeOrSpeedField;
            }
            set
            {
                this.favorSizeOrSpeedField = value;
            }
        }

        /// <observações/>
        public string StringPooling
        {
            get
            {
                return this.stringPoolingField;
            }
            set
            {
                this.stringPoolingField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
    public partial class Import
    {

        private string projectField;

        private string conditionField;

        private string labelField;

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
    public partial class Project
    {

        private ProjectItemGroup[] itemGroupField;

        private ProjectPropertyGroup[] propertyGroupField;

        private Import[] importField;

        private ProjectImportGroup[] importGroupField;

        private ProjectItemDefinitionGroup[] itemDefinitionGroupField;

        private string defaultTargetsField;

        private string toolsVersionField;

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup")]
        public ProjectItemGroup[] ItemGroup
        {
            get
            {
                return this.itemGroupField;
            }
            set
            {
                this.itemGroupField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup")]
        public ProjectPropertyGroup[] PropertyGroup
        {
            get
            {
                return this.propertyGroupField;
            }
            set
            {
                this.propertyGroupField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("Import")]
        public Import[] Import
        {
            get
            {
                return this.importField;
            }
            set
            {
                this.importField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ImportGroup")]
        public ProjectImportGroup[] ImportGroup
        {
            get
            {
                return this.importGroupField;
            }
            set
            {
                this.importGroupField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ItemDefinitionGroup")]
        public ProjectItemDefinitionGroup[] ItemDefinitionGroup
        {
            get
            {
                return this.itemDefinitionGroupField;
            }
            set
            {
                this.itemDefinitionGroupField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultTargets
        {
            get
            {
                return this.defaultTargetsField;
            }
            set
            {
                this.defaultTargetsField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ToolsVersion
        {
            get
            {
                return this.toolsVersionField;
            }
            set
            {
                this.toolsVersionField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroup
    {

        private ProjectItemGroupProjectReference[] projectReferenceField;

        private ResourceCompile[] resourceCompileField;

        private ProjectItemGroupImage[] imageField;

        private ProjectItemGroupNone[] noneField;

        private ClCompile[] clCompileField;

        private ProjectItemGroupClInclude[] clIncludeField;

        private ProjectItemGroupProjectConfiguration[] projectConfigurationField;

        private string labelField;

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectReference")]
        public ProjectItemGroupProjectReference[] ProjectReference
        {
            get
            {
                return this.projectReferenceField;
            }
            set
            {
                this.projectReferenceField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ResourceCompile")]
        public ResourceCompile[] ResourceCompile
        {
            get
            {
                return this.resourceCompileField;
            }
            set
            {
                this.resourceCompileField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("Image")]
        public ProjectItemGroupImage[] Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("None")]
        public ProjectItemGroupNone[] None
        {
            get
            {
                return this.noneField;
            }
            set
            {
                this.noneField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ClCompile")]
        public ClCompile[] ClCompile
        {
            get
            {
                return this.clCompileField;
            }
            set
            {
                this.clCompileField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ClInclude")]
        public ProjectItemGroupClInclude[] ClInclude
        {
            get
            {
                return this.clIncludeField;
            }
            set
            {
                this.clIncludeField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectConfiguration")]
        public ProjectItemGroupProjectConfiguration[] ProjectConfiguration
        {
            get
            {
                return this.projectConfigurationField;
            }
            set
            {
                this.projectConfigurationField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupProjectReference
    {

        private string projectField;

        private string privateField;

        private string referenceOutputAssemblyField;

        private string copyLocalSatelliteAssembliesField;

        private string linkLibraryDependenciesField;

        private string useLibraryDependencyInputsField;

        private string includeField;

        /// <observações/>
        public string Project
        {
            get
            {
                return this.projectField;
            }
            set
            {
                this.projectField = value;
            }
        }

        /// <observações/>
        public string Private
        {
            get
            {
                return this.privateField;
            }
            set
            {
                this.privateField = value;
            }
        }

        /// <observações/>
        public string ReferenceOutputAssembly
        {
            get
            {
                return this.referenceOutputAssemblyField;
            }
            set
            {
                this.referenceOutputAssemblyField = value;
            }
        }

        /// <observações/>
        public string CopyLocalSatelliteAssemblies
        {
            get
            {
                return this.copyLocalSatelliteAssembliesField;
            }
            set
            {
                this.copyLocalSatelliteAssembliesField = value;
            }
        }

        /// <observações/>
        public string LinkLibraryDependencies
        {
            get
            {
                return this.linkLibraryDependenciesField;
            }
            set
            {
                this.linkLibraryDependenciesField = value;
            }
        }

        /// <observações/>
        public string UseLibraryDependencyInputs
        {
            get
            {
                return this.useLibraryDependencyInputsField;
            }
            set
            {
                this.useLibraryDependencyInputsField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupImage
    {

        private string includeField;

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupNone
    {

        private string includeField;

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupClInclude
    {

        private string includeField;

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupProjectConfiguration
    {

        private string configurationField;

        private string platformField;

        private string includeField;

        /// <observações/>
        public string Configuration
        {
            get
            {
                return this.configurationField;
            }
            set
            {
                this.configurationField = value;
            }
        }

        /// <observações/>
        public string Platform
        {
            get
            {
                return this.platformField;
            }
            set
            {
                this.platformField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectPropertyGroup
    {

        private string configurationTypeField;

        private string useDebugLibrariesField;

        private string platformToolsetField;

        private string wholeProgramOptimizationField;

        private string characterSetField;

        private string projectGuidField;

        private string rootNamespaceField;

        private string outDirField;

        private string targetNameField;

        private string linkIncrementalField;

        private string labelField;

        private string conditionField;

        /// <observações/>
        public string ConfigurationType
        {
            get
            {
                return this.configurationTypeField;
            }
            set
            {
                this.configurationTypeField = value;
            }
        }

        /// <observações/>
        public string UseDebugLibraries
        {
            get
            {
                return this.useDebugLibrariesField;
            }
            set
            {
                this.useDebugLibrariesField = value;
            }
        }

        /// <observações/>
        public string PlatformToolset
        {
            get
            {
                return this.platformToolsetField;
            }
            set
            {
                this.platformToolsetField = value;
            }
        }

        /// <observações/>
        public string WholeProgramOptimization
        {
            get
            {
                return this.wholeProgramOptimizationField;
            }
            set
            {
                this.wholeProgramOptimizationField = value;
            }
        }

        /// <observações/>
        public string CharacterSet
        {
            get
            {
                return this.characterSetField;
            }
            set
            {
                this.characterSetField = value;
            }
        }

        /// <observações/>
        public string ProjectGuid
        {
            get
            {
                return this.projectGuidField;
            }
            set
            {
                this.projectGuidField = value;
            }
        }

        /// <observações/>
        public string RootNamespace
        {
            get
            {
                return this.rootNamespaceField;
            }
            set
            {
                this.rootNamespaceField = value;
            }
        }

        /// <observações/>
        public string OutDir
        {
            get
            {
                return this.outDirField;
            }
            set
            {
                this.outDirField = value;
            }
        }

        /// <observações/>
        public string TargetName
        {
            get
            {
                return this.targetNameField;
            }
            set
            {
                this.targetNameField = value;
            }
        }

        /// <observações/>
        public string LinkIncremental
        {
            get
            {
                return this.linkIncrementalField;
            }
            set
            {
                this.linkIncrementalField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectImportGroup
    {

        private Import[] importField;

        private string labelField;

        private string conditionField;

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("Import")]
        public Import[] Import
        {
            get
            {
                return this.importField;
            }
            set
            {
                this.importField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemDefinitionGroup
    {

        private ClCompile[] clCompileField;

        private ProjectItemDefinitionGroupLink[] linkField;

        private ResourceCompile[] resourceCompileField;

        private string conditionField;

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ClCompile")]
        public ClCompile[] ClCompile
        {
            get
            {
                return this.clCompileField;
            }
            set
            {
                this.clCompileField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("Link")]
        public ProjectItemDefinitionGroupLink[] Link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ResourceCompile")]
        public ResourceCompile[] ResourceCompile
        {
            get
            {
                return this.resourceCompileField;
            }
            set
            {
                this.resourceCompileField = value;
            }
        }

        /// <observações/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition
        {
            get
            {
                return this.conditionField;
            }
            set
            {
                this.conditionField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemDefinitionGroupLink
    {

        private string generateDebugInformationField;

        private string enableCOMDATFoldingField;

        private string optimizeReferencesField;

        private string additionalLibraryDirectoriesField;

        private string ignoreAllDefaultLibrariesField;

        private string ignoreSpecificDefaultLibrariesField;

        private string uACExecutionLevelField;

        private string subSystemField;

        private string largeAddressAwareField;

        private string randomizedBaseAddressField;

        private string imageHasSafeExceptionHandlersField;

        private string programDatabaseFileField;

        private string generateMapFileField;

        private string mapFileNameField;

        private string mapExportsField;

        private string linkTimeCodeGenerationField;

        /// <observações/>
        public string GenerateDebugInformation
        {
            get
            {
                return this.generateDebugInformationField;
            }
            set
            {
                this.generateDebugInformationField = value;
            }
        }

        /// <observações/>
        public string EnableCOMDATFolding
        {
            get
            {
                return this.enableCOMDATFoldingField;
            }
            set
            {
                this.enableCOMDATFoldingField = value;
            }
        }

        /// <observações/>
        public string OptimizeReferences
        {
            get
            {
                return this.optimizeReferencesField;
            }
            set
            {
                this.optimizeReferencesField = value;
            }
        }

        /// <observações/>
        public string AdditionalLibraryDirectories
        {
            get
            {
                return this.additionalLibraryDirectoriesField;
            }
            set
            {
                this.additionalLibraryDirectoriesField = value;
            }
        }

        /// <observações/>
        public string IgnoreAllDefaultLibraries
        {
            get
            {
                return this.ignoreAllDefaultLibrariesField;
            }
            set
            {
                this.ignoreAllDefaultLibrariesField = value;
            }
        }

        /// <observações/>
        public string IgnoreSpecificDefaultLibraries
        {
            get
            {
                return this.ignoreSpecificDefaultLibrariesField;
            }
            set
            {
                this.ignoreSpecificDefaultLibrariesField = value;
            }
        }

        /// <observações/>
        public string UACExecutionLevel
        {
            get
            {
                return this.uACExecutionLevelField;
            }
            set
            {
                this.uACExecutionLevelField = value;
            }
        }

        /// <observações/>
        public string SubSystem
        {
            get
            {
                return this.subSystemField;
            }
            set
            {
                this.subSystemField = value;
            }
        }

        /// <observações/>
        public string LargeAddressAware
        {
            get
            {
                return this.largeAddressAwareField;
            }
            set
            {
                this.largeAddressAwareField = value;
            }
        }

        /// <observações/>
        public string RandomizedBaseAddress
        {
            get
            {
                return this.randomizedBaseAddressField;
            }
            set
            {
                this.randomizedBaseAddressField = value;
            }
        }

        /// <observações/>
        public string ImageHasSafeExceptionHandlers
        {
            get
            {
                return this.imageHasSafeExceptionHandlersField;
            }
            set
            {
                this.imageHasSafeExceptionHandlersField = value;
            }
        }

        /// <observações/>
        public string ProgramDatabaseFile
        {
            get
            {
                return this.programDatabaseFileField;
            }
            set
            {
                this.programDatabaseFileField = value;
            }
        }

        /// <observações/>
        public string GenerateMapFile
        {
            get
            {
                return this.generateMapFileField;
            }
            set
            {
                this.generateMapFileField = value;
            }
        }

        /// <observações/>
        public string MapFileName
        {
            get
            {
                return this.mapFileNameField;
            }
            set
            {
                this.mapFileNameField = value;
            }
        }

        /// <observações/>
        public string MapExports
        {
            get
            {
                return this.mapExportsField;
            }
            set
            {
                this.mapExportsField = value;
            }
        }

        /// <observações/>
        public string LinkTimeCodeGeneration
        {
            get
            {
                return this.linkTimeCodeGenerationField;
            }
            set
            {
                this.linkTimeCodeGenerationField = value;
            }
        }
    }

    /// <observações/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/developer/msbuild/2003", IsNullable = false)]
    public partial class VCXProjectFile
    {

        private object[] itemsField;

        /// <observações/>
        [System.Xml.Serialization.XmlElementAttribute("ClCompile", typeof(ClCompile))]
        [System.Xml.Serialization.XmlElementAttribute("Import", typeof(Import))]
        [System.Xml.Serialization.XmlElementAttribute("Project", typeof(Project))]
        [System.Xml.Serialization.XmlElementAttribute("ResourceCompile", typeof(ResourceCompile))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }


        ////////////////////////////

        public static T DeserializeToObject<T>(string filepath) where T : VCXProjectFile
        {
            System.Xml.Serialization.XmlSerializer ser = new System.Xml.Serialization.XmlSerializer(typeof(T));

            using (StreamReader sr = new StreamReader(filepath))
            {
                return (T)ser.Deserialize(sr);
            }
        }
    }

}
